import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Shahroz",
      email: "shahrozahmed787@gmail.com",
      password: bcrypt.hashSync("12345678"),
      isAdmin: true,
    },

    {
      name: "Shahroz Ahmed",
      email: "shahrozahmed453@gmail.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Sony WH-1000XM3 Bluetooth Wireless Over Ear Headphones with Mic (Silver)",
      slug: "sony-wh-1000xm3-bluetooth-wireless-over-ear-headphones-with-mic-silver",
      image: "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1692947383286-714WUJlhbLS._SL1500_.jpg",
      brand: "sony",
      category: "audio",
      description: "Industry-leading noise cancellation, Hi-Res Audio, powerful 40mm drivers, Alexa built-in, frequency response 4 Hz-40 kHz.",
      price: 773,
      countInStock: 20,
      rating: 4.5,
      numReviews: 1342
    },
    {
      name: "Microsoft Xbox X/S Wireless Controller Robot White",
      slug: "microsoft-xbox-xs-wireless-controller-robot-white",
      image: "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1692255251854-xbox.jpg",
      brand: "microsoft",
      category: "gaming",
      description: "Modern design with textured grips, hybrid D-pad, customizable buttons via Xbox accessories app.",
      price: 57,
      countInStock: 20,
      rating: 4.5,
      numReviews: 982
    },
    {
      name: "Logitech G733 Lightspeed Wireless Gaming Headset - White",
      slug: "logitech-g733-lightspeed-wireless-gaming-headset-white",
      image: "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1692257709689-logitech%20heaphone.jpg",
      brand: "logitech G",
      category: "gaming",
      description: "Wireless range up to 20m, 29-hour battery, RGB lighting, PRO-G drivers, advanced mic filters, lightweight comfort.",
      price: 384,
      countInStock: 20,
      rating: 4.5,
      numReviews: 643
    },
    {
      name: "Sony WH-1000XM5 Wireless Industry Leading Active Noise Cancelling Headphones",
      slug: "sony-wh-1000xm5-wireless-industry-leading-active-noise-cancelling-headphones-8-mics-for-clear-calling-30hr-battery-3-min-quick-charge-3-hours-playback-multi-point-connectivity-alexa-silver",
      image: "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1692941008275-headphone3.jpg",
      brand: "sony",
      category: "audio",
      description: "Advanced noise cancellation with 8 mics, Auto NC Optimizer, clear calls with AI noise reduction, crystal-clear sound.",
      price: 362,
      countInStock: 20,
      rating: 4.5,
      numReviews: 1182
    },
    {
      name: "Urbanista Los Angeles Sand Gold - Solar Powered Hybrid Active Noise Cancelling Headphones",
      slug: "urbanista-los-angeles-sand-gold-world-s-1st-solar-powered-hybrid-active-noise-cancelling-with-mic-premium-wireless-headphones-unlimited-playtime",
      image: "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1691056487173-headphon2.jpg",
      brand: "urbanista",
      category: "audio",
      description: "World's first solar-powered headphones with hybrid ANC, unlimited playtime, Ambient Sound Mode.",
      price: 265,
      countInStock: 20,
      rating: 4.5,
      numReviews: 642
    },
    {
      name: "Xiaomi Wired in-Ear Earphones with Mic, Ultra Deep Bass & Metal Sound Chamber (Blue)",
      slug: "xiaomi-wired-in-ear-earphones-with-mic-ultra-deep-bass-metal-sound-chamber-blue",
      image: "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1691057474498-earphone.jpg",
      brand: "xiaomi",
      category: "audio",
      description: "Ergonomic design, 1.25m cable, L-shaped jack, powerful 10mm drivers, in-line mic with multi-function button.",
      price: 5,
      countInStock: 20,
      rating: 4.5,
      numReviews: 889
    },
    {
      name: "boAt Rockerz 370 On Ear Bluetooth Headphones with Mic (Buoyant Black)",
      slug: "boat-rockerz-370-on-ear-bluetooth-headphones-with-upto-12-hours-playtime-cozy-padded-earcups-and-bluetooth-v5-0-with-mic-buoyant-black",
      image: "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1691057718636-headphone5.jpg",
      brand: "boat",
      category: "audio",
      description: "Bluetooth v5.0, up to 8 hours playtime, 40mm drivers, padded earcups, dual connectivity Bluetooth & AUX.",
      price: 12,
      countInStock: 20,
      rating: 4.5,
      numReviews: 112
    },
    
    {
      name: "Amkette EvoFox Elite Ops Wireless Gamepad for Android TV",
      slug: "amkette-evofox-elite-ops-wireless-gamepad-for-android-tv-google-tv-8-hours-of-play-time-zero-lag-connectivity-upto-12-feets-usb-extender-for-tv-included-dusk-grey",
      image: "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1694100438525-51Prg4Smx-L._SL1500_.jpg",
      brand: "Amkette",
      category: "gaming",
      description: "Wireless gamepad with Type-C charging, 8+ hours playtime, zero lag, supports Android TV, Windows, PS3.",
      price: 18,
      countInStock: 20,
      rating: 4.5,
      numReviews: 225
    },
    {
      name: "Samsung Galaxy S22 5G (Phantom White, 8GB RAM, 128GB Storage)",
      slug: "samsung-galaxy-s22-5g-phantom-white-8gb-ram-128gb-storage-with-no-cost-emi-additional-exchange-offers",
      image: "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1691074519203-galaxy%20S22%205G.jpg",
      brand: "samsung",
      category: "mobile",
      description: "120Hz AMOLED display, powerful 4nm processor, Nightography camera, Gorilla Glass Victus+, sleek design.",
      price: 760,
      countInStock: 20,
      rating: 4.5,
      numReviews: 446
    },

    {
      name: "Samsung Galaxy S22 Ultra 5G (Burgundy, 12GB, 256GB Storage) ",
      slug: "samsung-galaxy-s22-ultra-5g-burgundy-12gb-256gb-storage",
      image: "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1691074776147-galaxy%20S22%20ultra%205G.jpg",
      brand: "samsung",
      category: "mobile",
      description: "Embedded S Pen, 5G, fast 4nm processor, Dynamic AMOLED 2x display with 120Hz refresh rate.",
      price: 1147,
      countInStock: 20,
      rating: 4.5,
      numReviews: 668
    },
    {
      name: "Poco by Xiaomi F1 Steel Blue, 6GB RAM, 64GB Storage",
      slug: "poco-by-xiaomi-f1-steel-blue-6gb-ram-64gb-storage",
      image: "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1691078463674-poco%20f1.jpg",
      brand: "xiaomi",
      category: "mobile",
      description: "Dual camera, 6.18 IPS display, Snapdragon 845 processor, 4000mAh battery, Android Oreo.",
      price: 132,
      countInStock: 20,
      rating: 4.5,
      numReviews: 1275
    },
    {
      name: "Samsung Galaxy M14 5G (Smoky Teal, 6GB, 128GB Storage)",
      slug: "samsung-galaxy-m14-5g-smoky-teal-6gb-128gb-storage",
      image: "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1691075307831-galaxy%20M14%205G.jpg",
      brand: "samsung",
      category: "mobile",
      description: "Dual camera, 6.18 IPS display, Snapdragon 845 processor, 4000mAh battery, Android Oreo.",
      price: 187,
      countInStock: 20,
      rating: 4.5,
      numReviews: 551
    },
    
    {
      name: "Apple iPhone 14 Pro Max (256 GB) - Deep Purple",
      slug: "apple-iphone-14-pro-max-256-gb-deep-purple",
      image: "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1691075831385-iPhone%2014%20pro%20max.jpg",
      brand: "apple",
      category: "mobile",
      description: "6.7 Super Retina XDR, Dynamic Island, 48MP camera, cinematic 4K video, crash detection, long battery.",
      price: 1810,
      countInStock: 20,
      rating: 4.5,
      numReviews: 223
    },
    {
      name: "Apple iPhone 14 Pro (256 GB) - Gold",
      slug: "apple-iphone-14-pro-256-gb-gold",
      image: "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1691076020478-iPhone%2014%20pro.jpg",
      brand: "apple",
      category: "mobile",
      description: "6.1 Super Retina XDR, Dynamic Island, 48MP camera, cinematic 4K video, crash detection.",
      price: 1546,
      countInStock: 20,
      rating: 4.5,
      numReviews: 449
    },
   
    {
      name: "Xiaomi 12 Pro | 5G (Noir Black, 8GB RAM, 256GB Storage) | Snapdragon 8 Gen 1 | 50+50+50MP Flagship Cameras (OIS) | 10bit 2K+ Curved AMOLED Display",
      slug: "xiaomi-12-pro-5g-noir-black-8gb-ram-256gb-storage-snapdragon-8-gen-1-50-50-50mp-flagship-cameras-ois-10bit-2k-curved-amoled-display",
      image: "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1691077711136-xiaomi%2012%20pro%205g.jpg",
      brand: "xiaomi",
      category: "mobile",
      description: "Triple 50MP cameras, 6.73 120Hz AMOLED, Snapdragon 8 Gen 1, 4600mAh battery with 120W charge.",
      price: 507,
      countInStock: 20,
      rating: 4.5,
      numReviews: 999
    },
    {
      name: " Xiaomi 11T Pro 5G Hyperphone (Meteorite Black, 8GB RAM, 256GB Storage) |SD 888|120W HyperCharge|Segment's only Phone with Dolby Vision+Dolby Atmos",
      slug: "xiaomi-11t-pro-5g-hyperphone-meteorite-black-8gb-ram-256gb-storage-sd-888-120w-hypercharge-segment-s-only-phone-with-dolby-vision-dolby-atmos",
      image: "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1691078241728-xiaomi%2011T%20Pro%205G.jpg",
      brand: "xiaomi",
      category: "mobile",
      description: "Snapdragon 888, 6.67 120Hz AMOLED, 108MP camera, 8K video, Dolby Vision & Atmos, 120W HyperCharge.",
      price: 507,
      countInStock: 20,
      rating: 4.5,
      numReviews: 1234
    },
    {
      name: "Samsung Galaxy M13 (Aqua Green, 6GB, 128GB Storage)",
      slug: "samsung-galaxy-m13-aqua-green-6gb-128gb-storage",
      image: "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1691075065521-galaxy%20M13.jpg",
      brand: "samsung",
      category: "mobile",
      description: "6.6 FHD+ LCD, 50MP triple camera, up to 12GB RAM, 6000mAh battery, Android 12.",
      price: 140,
      countInStock: 20,
      rating: 4.5,
      numReviews: 335
    },
    {
      name: "Redmi Note 12 5G Matte Black 6GB RAM 128GB ROM | 1st Phone with 120Hz Super AMOLED and Snapdragon® 4 Gen 1 | 48MP AI Triple Camera",
      slug: "redmi-note-12-5g-matte-black-6gb-ram-128gb-rom-1st-phone-with-120hz-super-amoled-and-snapdragon-4-gen-1-48mp-ai-triple-camera",
      image: "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1691078965685-redmi%20note%2012%205g.jpg",
      brand: "xiaomi",
      category: "mobile",
      description: "6GB RAM, 128GB storage, Snapdragon 4 Gen1, 48MP AI triple camera, 120Hz Super AMOLED display, 5000mAh battery with 33W fast charging.",
      price: 229,
      countInStock: 20,
      rating: 4.5,
      numReviews: 3335
    },
    {
      name: "Sennheiser HD 400s Wired Over The Ear Headphone with Mic (Black)",
      slug: "sennheiser-hd-400s-wired-over-the-ear-headphone-with-mic-black",
      image: "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1691055730759-headphone4.jpg",
      brand: "Sennheiser",
      category: "audio",
      description: "High-quality wired headphones with built-in mic, remote control, noise isolation, lightweight and foldable design.",
      price: 54,
      countInStock: 20,
      rating: 4.5,
      numReviews: 336
    },
    {
      name: "Ant Esports GP310 Wireless Gamepad, Compatible for PC & Laptop (Windows 10/8 /7, Steam) / PS3 / Android",
      slug: "ant-esports-gp310-wireless-gamepad-compatible-for-pc-laptop-windows-10-8-7-steam-ps3-android",
      image: "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1692255692675-ant%20sport.jpg",
      brand: "ant esports",
      category: "gaming",
      description: "Wireless gamepad with 2.4GHz tech, multi-mode support (PC, Android, PS3), vibration feedback, and ergonomic design.",
      price: 14,
      countInStock: 20,
      rating: 4.5,
      numReviews: 446
    },
    {
      name: "Logitech G502 Lightspeed Wireless Gaming Mouse, 25K Hero Gaming Sensor, 25600 DPI, RGB, Ultra-Light, 11 Programmable Buttons, Long Life Battery, PowerPlay-Compatible, PC - Black",
      slug: "logitech-g502-lightspeed-wireless-gaming-mouse-25k-hero-gaming-sensor-25600-dpi-rgb-ultra-light-11-programmable-buttons-long-life-battery-powerplay-compatible-pc-black",
      image: "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1692257315660-logitech.jpg",
      brand: "logitech G",
      category: "gaming",
      description: "Wireless RGB gaming mouse with 25K sensor, 11 programmable buttons, mechanical spring tensioning, and long battery life.",
      price: 19,
      countInStock: 20,
      rating: 4.5,
      numReviews: 446
    },
    {
      name: "Samsung Galaxy S23 5G (Green, 8GB, 128GB Storage)",
      slug: "samsung-galaxy-s23-5g-green-8gb-128gb-storage",
      image: "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1691074179466-galaxy%20S23%205G.jpg",
      brand: "samsung",
      category: "mobile",
      description: "8GB RAM, 128GB storage, Snapdragon 8 Gen 2, enhanced AI night photography, eco-friendly design.",
      price: 905,
      countInStock: 20,
      rating: 4.5,
      numReviews: 336
    },
    {
      name: "Handheld Game Console 5.1 inch Pro Retro Games Consoles Built-in Classic Games Rechargeable Battery Portable Style Game Consoles X12",
      slug: "handheld-game-console-5-1-inch-pro-retro-games-consoles-built-in-classic-games-rechargeable-battery-portable-style-game-consoles-x12",
      image: "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1692458709910-51DkZC39goL._SL1000_.jpg",
      brand: "CredevZone",
      category: "gaming",
      description: "Portable 5.1-inch handheld console with 900+ built-in classic games, rechargeable battery, and multimedia features.",
      price: 163,
      countInStock: 20,
      rating: 4.5,
      numReviews: 773
    },
    
    {
      name: "Apple AirPods (3rd Generation) with Lightning Charging Case ​​​​​​​",
      slug: "apple-airpods-3rd-generation-with-lightning-charging-case",
      image: "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1691054448465-earbud2.jpg",
      brand: "apple",
      category: "audio",
      description: "3rd Gen AirPods with spatial audio, adaptive EQ, and redesigned contoured fit for immersive sound.",
      price: 230,
      countInStock: 20,
      rating: 4.5,
      numReviews: 881
    },
    {
      name: "Sony WH-CH520, Wireless On-Ear Bluetooth Headphones with Mic, Upto 50 Hours Playtime, DSEE Upscale, Multipoint Connectivity/Dual Pairing,Voice Assistant App Support for Mobile Phones (Blue)",
      slug: "sony-wh-ch520-wireless-on-ear-bluetooth-headphones-with-mic-upto-50-hours-playtime-dsee-upscale-multipoint-connectivity-dual-pairing-voice-assistant-app-support-for-mobile-phones-blue",
      image: "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1692939683873-headphone1.jpg",
      brand: "sony",
      category: "audio",
      description: "Wireless Bluetooth headphones with 50-hour battery, DSEE sound enhancement, multipoint connection, and built-in mic.",
      price: 60,
      countInStock: 20,
      rating: 4.5,
      numReviews: 227
    },
    {
      name: "Sony Srs-Xb13 Wireless Extra Bass Portable Compact Bluetooth Speaker with 16 Hours Battery Life, Type-C, Ip67 Waterproof, Dustproof, with Mic, Loud Audio for Phone Calls/Work from Home (Black), Small",
      slug: "sony-srs-xb13-wireless-extra-bass-portable-compact-bluetooth-speaker-with-16-hours-battery-life-type-c-ip67-waterproof-dustproof-with-mic-loud-audio-for-phone-calls-work-from-home-black-small",
      image: "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1692940742197-speaker1.jpg",
      brand: "sony",
      category: "audio",
      description: "Compact waterproof Bluetooth speaker with extra bass, 16-hour battery, Type-C charging, and built-in mic for calls.",
      price: 42,
      countInStock: 20,
      rating: 4.5,
      numReviews: 224
    },


    {
      name: "Panasonic RB-M300B Deep Bass Wireless Bluetooth Immersive Headphones (Sand Beige)",
      slug: "panasonic-rb-m300b-deep-bass-wireless-bluetooth-immersive-headphones-sand-beige",
      image: "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1691056086962-headphone.jpg",
      brand: "panasonic",
      category: "audio",
      description: "Powerful deep bass with balanced sound. Wireless Bluetooth with mic. 50 hours playback on 4-hour charge. Dual 40mm drivers. Soft cushioned headband for comfort.",
      price: 289,
      countInStock: 20,
      rating: 4.5,
      numReviews: 337
    },
    {
      name: "Sony WH-CH520 Wireless On-Ear Bluetooth Headphones with Mic (Beige)",
      slug: "sony-wh-ch520-wireless-on-ear-bluetooth-headphones-beige",
      image: "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1692941955003-headphone2.jpg",
      brand: "sony",
      category: "audio",
      description: "Up to 50-hour battery with quick charge. Customizable sound via Sony app. Boosts compressed music quality with DSEE. Lightweight and comfortable.",
      price: 54,
      countInStock: 20,
      rating: 4.5,
      numReviews: 224
    },
    {
      name: "boAt Stone 180 5W Bluetooth Speaker with Upto 10 Hours Playback (Black)",
      slug: "boat-stone-180-5w-bluetooth-speaker-black",
      image: "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1692943845065-71vI6nfLtYL._SL1500_.jpg",
      brand: "boat",
      category: "audio",
      description: "Powerful 5W HD sound with 1.75\" drivers. 10-hour battery life, Bluetooth 5.0, IPX7 waterproof, and TWS feature to pair two speakers.",
      price: 13,
      countInStock: 20,
      rating: 4.5,
      numReviews: 994
    },
    {
      name: "Mivi Play Bluetooth Speaker with 12 Hours Playtime (Black)",
      slug: "mivi-play-bluetooth-speaker-black",
      image: "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1692944238682-61UJnlIHF9S._SL1500_.jpg",
      brand: "mivi",
      category: "audio",
      description: "Deep, powerful studio-grade sound with solid bass. 12 hours battery life. Sleek portable design. Bluetooth 5.0 for strong wireless connection.",
      price: 10,
      countInStock: 20,
      rating: 4.5,
      numReviews: 111
    },
    {
      name: "JBL Go 2 Wireless Portable Bluetooth Speaker with Mic (Blue)",
      slug: "jbl-go-2-wireless-portable-bluetooth-speaker-blue",
      image: "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1692944486283-8193DNNjZFS._SL1500_.jpg",
      brand: "JBL",
      category: "audio",
      description: "JBL signature sound with 5 hours playback. Wireless streaming, IPX7 waterproof, noise-cancelling mic, and AUX input.",
      price: 24,
      countInStock: 20,
      rating: 4.5,
      numReviews: 778
    },
    {
      name: "Mivi Duopods A25 Truly Wireless Earbuds with Mic (White)",
      slug: "mivi-duopods-a25-truly-wireless-earbuds-white",
      image: "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1692945068061-61yTSVeLebS._SL1500_.jpg",
      brand: "Mivi",
      category: "audio",
      description: "Made in India wireless earbuds with 40 hours battery, 13mm bass drivers, immersive sound, voice assistant and touch control.",
      price: 12,
      countInStock: 20,
      rating: 4.5,
      numReviews: 127
    },
    {
      name: "soundcore by Anker Space Q45 Adaptive Noise Cancelling Headphones",
      slug: "soundcore-by-anker-space-q45-adaptive-noise-cancelling-headphones",
      image: "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1691056348236-headphone3.jpg",
      brand: "soundcore",
      category: "audio",
      description: "Reduces noise up to 98%. Adaptive noise cancelling with 5 levels. Up to 50 hours playtime, 65 hours normal mode, quick charge support.",
      price: 415,
      countInStock: 20,
      rating: 4.5,
      numReviews: 552
    },
    {
      name: "Marshall Uxbridge Airplay Multi-Room Wireless Speaker with Alexa - White",
      slug: "marshall-uxbridge-airplay-multi-room-wireless-speaker-white",
      image: "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1692946110280-81WIcjaGp2L._SL1500_.jpg",
      brand: "Marshall",
      category: "audio",
      description: "Compact powerful sound with Alexa built-in. Multi-room and Airplay 2 support. Control music and smart devices via voice.",
      price: 266,
      countInStock: 20,
      rating: 4.5,
      numReviews: 225
    },
    {
      name: "Bang & Olufsen Beosound Balance Wireless Multiroom Speaker, Natural Oak",
      slug: "bang-olufsen-beosound-balance-wireless-multiroom-speaker-oak",
      image: "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1692946673658-91xz5VkenTL._SL1500_.jpg",
      brand: "Bang & Olufsen",
      category: "audio",
      description: "Wireless speaker with powerful, dynamic sound for large spaces. Elegant design with natural oak, textile and aluminium. Ideal for wall placement.",
      price: 5804,
      countInStock: 20,
      rating: 4.5,
      numReviews: 111
    },
    {
      name: "JBL Tune 720BT Wireless Over Ear Headphones with Mic (Blue)",
      slug: "jbl-tune-720bt-wireless-over-ear-headphones-blue",
      image: "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1691055458260-headphone.jpg",
      brand: "jbl",
      category: "audio",
      description: "JBL Pure Bass sound with up to 76 hours playback. Quick charge, dual pairing, customizable bass via app, lightweight with Bluetooth 5.3.",
      price: 100,
      countInStock: 20,
      rating: 4.5,
      numReviews: 557
    },


    {
      name: "Sony SA-SW5 300W Wireless Subwoofer for HT-A9 and HT-A7000 - Black",
      slug: "sony-sa-sw5-300w-wireless-subwoofer-for-ht-a9-and-ht-a7000-black",
      image: "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1692947684843-61T7iilajhL._SL1200_.jpg",
      brand: "sony",
      category: "audio",
      description: "Powerful 300W bass wireless subwoofer for HT-A9 & HT-A7000 soundbars with easy setup.",
      price: 629,
      countInStock: 20,
      rating: 4.5,
      numReviews: 228
    },
    {
      name: "DENON Home 350 Wireless Speaker - Powerful Room Filling Sound with Bluetooth, AirPlay 2 and Alexa Built-in - White",
      slug: "denon-home-350-wireless-speaker-powerful-room-filling-sound-with-bluetooth-airplay-2-and-alexa-built-in-white",
      image: "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1692947856684-81xoxBiCcjL._SL1500_.jpg",
      brand: "Denon",
      category: "audio",
      description: "Powerful wireless speaker with Bluetooth, AirPlay 2, Alexa, and stereo pairing capability.",
      price: 919,
      countInStock: 20,
      rating: 4.5,
      numReviews: 942
    },
    {
      name: "JBL Wave 200 Wireless Earbuds (TWS) with Mic, 20 Hours Playtime, Deep Bass Sound, Dual Connect Technology, Quick Charge, Comfort Fit Ergonomic Design, Voice Assistant Support for Mobiles (Black)",
      slug: "jbl-wave-200-wireless-earbuds-tws-with-mic-20-hours-playtime-deep-bass-sound-dual-connect-technology-quick-charge-comfort-fit-ergonomic-design-voice-assistant-support-for-mobiles-black",
      image: "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1691055343505-earbud.jpg",
      brand: "jbl",
      category: "audio",
      description: "Wireless earbuds with 20hrs playtime, deep bass, quick charge, dual connect, and voice assistant.",
      price: 24,
      countInStock: 20,
      rating: 4.5,
      numReviews: 567
    },
    {
      name: "Sony WF-C700N Bluetooth Truly Wireless Lightest Active Noise Cancellation in Ear Earbuds, Multipoint Connection, 10 mins Super Quick Charge, 20hrs Batt, IPX4 Ratings, Fast Pair, App Support-Black",
      slug: "sony-wf-c700n-bluetooth-truly-wireless-lightest-active-noise-cancellation-in-ear-earbuds-multipoint-connection-10-mins-super-quick-charge-20hrs-batt-ipx4-ratings-fast-pair-app-support-black",
      image: "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1692939913875-earphone1.jpg",
      brand: "sony",
      category: "audio",
      description: "Lightweight earbuds with ANC, multipoint Bluetooth, 20hr battery, fast charge, and app support.",
      price: 108,
      countInStock: 20,
      rating: 4.5,
      numReviews: 224
    },
    {
      name: "New Apple AirPods Max - Pink",
      slug: "new-apple-airpods-max-pink",
      image: "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1691053838595-headphone2.jpg",
      brand: "apple",
      category: "audio",
      description: "High-fidelity headphones with active noise cancellation, spatial audio, and memory foam cushions.",
      price: 723,
      countInStock: 20,
      rating: 4.5,
      numReviews: 224
    },
    {
      name: "Redmi 80 cm (32 inches) HD Ready Smart LED Fire TV L32R8-FVIN (Black)",
      slug: "redmi-80-cm-32-inches-hd-ready-smart-led-fire-tv-l32r8-fvin-black",
      image: "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1694154515879-819Lw2PE8tL._SL1500_.jpg",
      brand: "redmi",
      category: "tv",
      description: "32-inch HD Ready Smart TV with Fire TV, Alexa voice remote, and multiple connectivity options.",
      price: 138,
      countInStock: 20,
      rating: 4.5,
      numReviews: 888
    },
    {
      name: "Samsung 108 cm (43 inches) Crystal iSmart 4K Ultra HD Smart LED TV UA43CUE60AKLXL (Black)",
      slug: "samsung-108-cm-43-inches-crystal-ismart-4k-ultra-hd-smart-led-tv-ua43cue60aklxl-black",
      image: "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1694154827301-81+JXgPUDLL._SL1500_.jpg",
      brand: "samsung",
      category: "tv",
      description: "43-inch 4K Smart TV with popular apps, screen mirroring, AI speaker, and smart hub features.",
      price: 396,
      countInStock: 20,
      rating: 4.5,
      numReviews: 333
    },
    {
      name: "Mi 125 cm (50 inches) X Series 4K Ultra HD Smart Android LED TV L50M7-A2IN (Black)",
      slug: "mi-125-cm-50-inches-x-series-4k-ultra-hd-smart-android-led-tv-l50m7-a2in-black",
      image: "https://storage.googleapis.com/fir-auth-1c3bc.appspot.com/1694155239807-81UT46-gwRL._SL1500_.jpg",
      brand: "mi",
      category: "tv",
      description: "50-inch 4K Android Smart TV with Dolby Audio, Google Assistant, Chromecast, and wide app support.",
      price: 384,
      countInStock: 20,
      rating: 4.5,
      numReviews: 666
    },
   
  ]
};

export default data;